name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 18 * * *'
  workflow_dispatch:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        shell: bash
        run: npm ci

      - uses: oke-py/npm-audit-action@v3
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          audit_level: moderate
          github_token: $GH_TOKEN
          create_pr_comments: true
          create_issues: true
          issue_labels: vulnerability,test
          dedupe_issues: true

      - name: Run linting
        run: npm run lint

      - name: Run TypeScript compilation
        run: npm run compile

      - name: Run tests
        uses: GabrielBB/xvfb-action@v1
        with:
          run: npm test
