name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 18 * * *'
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: ./.github/actions/setupenv

    - name: Download VS Code
      run: npx @vscode/test-electron --version

    - name: Run linting
      run: npm run lint

    - name: Run TypeScript compilation
      run: npm run compile

    - name: Run tests
      run: npm test
